/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class MyStruct {
  field: number
  field1: number
  static withField(field: number): MyStruct
  getField(): number
}
