/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  ignoreBinPackage?: boolean | undefined | null
  ignorePatterns?: Array<string> | undefined | null
  ignoreMatches?: Array<string> | undefined | null
  skipMissing?: boolean | undefined | null
  ignorePath?: string | undefined | null
}
export interface DepcheckResult {
  usingDependencies: Record<string, Array<string>>
  missingDependencies: Record<string, Array<string>>
  unusedDependencies: Array<string>
  unusedDevDependencies: Array<string>
}
export function depcheck(path: string, options?: Options | undefined | null): DepcheckResult
