/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  ignoreBinPackage?: boolean
  ignorePatterns?: Array<string>
  ignoreMatches?: Array<string>
  skipMissing?: boolean
  ignorePath?: string
  verbose?: number
}
export interface DepcheckResult {
  usingDependencies: Record<string, Array<string>>
  missingDependencies: Record<string, Array<string>>
  unusedDependencies: Array<string>
  unusedDevDependencies: Array<string>
}
export function depcheck(path: string, options?: Options | undefined | null): DepcheckResult
